//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPRestaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesas
    {
        public int MesaID { get; set; }
        public Nullable<int> NumeroMesa { get; set; }
        public Nullable<int> CapacidadMaxima { get; set; }
        public string EstadoMesa { get; set; }
        public Nullable<int> ReservaID { get; set; }
    
        public virtual Reservas Reservas { get; set; }
    }
}
